version: "3.3"
services:
  mongo:
    image: mongo:5.0.2
    ports:
      - "27017:27017"
    volumes:
      - ~/mangilaspringbootrestfulservicemongodb:/data/db
  api:
    image: mangilaspringbootrestfulservice
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    links:
      - mongo
    depends_on:
      - mongo