#

executors:
j11:
  docker:
    - image: cimg/openjdk:11
    - steps:
        - checkout
        - run: echo "testcontainers.reuse.enable=true" >> testcontainers.properties

orbs:
  maven: circleci/maven@1.2.0
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: j11