version: 2.1

jobs:
  build:
    docker:
      - image: circleci/maven@1.2.0
    steps:
      - run: echo "testcontainers.reuse.enable=true" >> testcontainers.properties

workflows:
  maven_test:
    jobs:
      - build
      - maven/test