#

executors:
jdk11:
  docker:
    - image: 'adoptopenjdk/openjdk11:alpine-jre'
    - steps:
        - run: echo "testcontainers.reuse.enable=true" >> testcontainers.properties

orbs:
  maven: circleci/maven@1.2.0
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk11