version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    #  docker_layer_caching: true
    steps:
      - checkout
      - run: echo 'testcontainers.reuse.enable=true' >> /home/circleci/.testcontainers.properties
      - run: sudo apt-get install redis-server -y
      - run: mvn clean test