version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: echo 'testcontainers.reuse.enable=true' >> /home/circleci/.testcontainers.properties
      - run: mvn clean test